SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B 
  ON A.FISH_TYPE = B.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(IFNULL(LENGTH, 0)) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) M
  ON A.FISH_TYPE = M.FISH_TYPE
 AND IFNULL(A.LENGTH, 0) = M.MAX_LENGTH;